export const AVERAGE_PRICE = {
  EXAMPLE_AMOUNT: 123000,
  EXAMPLE_COMPARISON_AMOUNT: 16000,
  EXAMPLE_HAS_PREVIOUS_DATA: true,
  METRIC_LABEL: '주문',
  MIN_CHANGE_RATE: 0,
  MAX_CHANGE_RATE: 0,
} as const;
