export const LINE_CHART = {
  TICK_HEIGHT: 11,
  GUIDE_LINE_STROKE_WIDTH: 1.5,
  DOT_RADIUS: 2.5,
  LINE_STROKE_WIDTH: 1,
  XAXIS_STROKE_WIDTH: 1.5,
  XAXIS_RIGHT_OFFSET: 1,
  XAXIS_RIGHT_ARROW_X_OFFSET: 4,
  XAXIS_RIGHT_ARROW_Y_OFFSET: 4,
  XAXIS_Y_OFFSET: 28,
  GRADIENT_COLOR: '#009AFA',
  X_AXIS_LABEL_OFFSET: 5,
  GUIDE_LINE_DASH_ARRAY: '4 4',
};
