import type { DeepValueOf, ValueOf } from '@/utils/shared';

import { PERIOD_PRESETS } from '../shared';

const CHART_TYPE = {
  DOUGHNUT_CHART: 'donut_chart',
  BAR_CHART: 'analysis',
  LINE_CHART: 'line_graph',
  WEATHER: 'weather',
  RAIN: 'precipitation',
  NUMBER: 'number',
} as const;
type ChartType = ValueOf<typeof CHART_TYPE>;

interface MetricCard {
  code: string; // SLS_01_01
  label: string; // 오늘 실매출
  type: ChartType; // 시각화 유형
  period: DeepValueOf<typeof PERIOD_PRESETS>; // 오늘, 이번주 등
  sizeX: number; // 가로 크기 (기본값 1)
  sizeY: number; // 세로 크기 (기본값 1)
}

export const DASHBOARD_METRIC_CARDS = {
  SLS_01_01: {
    code: 'SLS_01_01',
    label: '오늘 실매출',
    type: CHART_TYPE.NUMBER,
    period: PERIOD_PRESETS.dayWeekMonth.today,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_01_02: {
    code: 'SLS_01_02',
    label: '이번주 실매출',
    type: CHART_TYPE.NUMBER,
    period: PERIOD_PRESETS.dayWeekMonth.thisWeek,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_01_03: {
    code: 'SLS_01_03',
    label: '이번달 실매출',
    type: CHART_TYPE.NUMBER,
    period: PERIOD_PRESETS.dayWeekMonth.thisMonth,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_02_01: {
    code: 'SLS_02_01',
    label: '오늘 주문건수',
    type: CHART_TYPE.NUMBER,
    period: PERIOD_PRESETS.dayWeekMonth.today,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_02_02: {
    code: 'SLS_02_02',
    label: '이번주 주문건수',
    type: CHART_TYPE.NUMBER,
    period: PERIOD_PRESETS.dayWeekMonth.thisWeek,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_02_03: {
    code: 'SLS_02_03',
    label: '이번달 주문건수',
    type: CHART_TYPE.NUMBER,
    period: PERIOD_PRESETS.dayWeekMonth.thisMonth,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_03_01: {
    code: 'SLS_03_01',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    label: '오늘 건당 평균가',
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_03_02: {
    code: 'SLS_03_02',
    period: PERIOD_PRESETS.dayWeekMonth.thisWeek,
    label: '이번주 건당 평균가',
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_03_03: {
    code: 'SLS_03_03',
    period: PERIOD_PRESETS.dayWeekMonth.thisMonth,
    label: '이번달 건당 평균가',
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_06_01: {
    code: 'SLS_06_01',
    label: '오늘 판매유형별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_06_02: {
    code: 'SLS_06_02',
    label: '이번주 판매유형별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.thisWeek,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_06_03: {
    code: 'SLS_06_03',
    label: '이번달 판매유형별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.thisMonth,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_07_01: {
    code: 'SLS_07_01',
    label: '오늘 주문수단별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_07_02: {
    code: 'SLS_07_02',
    label: '이번주 주문수단별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.thisWeek,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_07_03: {
    code: 'SLS_07_03',
    label: '이번달 주문수단별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.thisMonth,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_08_01: {
    code: 'SLS_08_01',
    label: '오늘 결제수단별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_08_02: {
    code: 'SLS_08_02',
    label: '이번주 결제수단별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.thisWeek,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_08_03: {
    code: 'SLS_08_03',
    label: '이번달 결제수단별 매출',
    period: PERIOD_PRESETS.dayWeekMonth.thisMonth,
    type: CHART_TYPE.DOUGHNUT_CHART,
    sizeX: 1,
    sizeY: 2,
  },
  SLS_09_04: {
    code: 'SLS_09_04',
    label: '일별 매출 추이',
    period: PERIOD_PRESETS.recentDays7_14_30.recent7Days,
    type: CHART_TYPE.BAR_CHART,
    sizeX: 3,
    sizeY: 1,
  },
  SLS_10_07: {
    code: 'SLS_10_07',
    label: '주별 매출 추이',
    period: PERIOD_PRESETS.recentDays7_14_30.recent14Days,
    type: CHART_TYPE.BAR_CHART,
    sizeX: 3,
    sizeY: 1,
  },
  SLS_11_07: {
    code: 'SLS_11_07',
    label: '월별 매출 추이',
    period: PERIOD_PRESETS.recentDays7_14_30.recent30Days,
    type: CHART_TYPE.BAR_CHART,
    sizeX: 2,
    sizeY: 1,
  },
  SLS_13_01: {
    code: 'SLS_13_01',
    label: '피크타임',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.LINE_CHART,
    sizeX: 1,
    sizeY: 1,
  },
  SLS_14_06: {
    code: 'SLS_14_06',
    label: '요일별 매출 패턴',
    period: PERIOD_PRESETS.recent4W.recent4Weeks,
    type: CHART_TYPE.BAR_CHART,
    sizeX: 1,
    sizeY: 1,
  },
  MNU_01_01: {
    code: 'MNU_01_01',
    label: '오늘 메뉴별 매출 랭킹',
    period: PERIOD_PRESETS.today7_30.today,
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  MNU_01_04: {
    code: 'MNU_01_04',
    label: '최근 7일 메뉴별 매출 랭킹',
    period: PERIOD_PRESETS.today7_30.recent7Days,
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  MNU_01_05: {
    code: 'MNU_01_05',
    label: '최근 30일 메뉴별 매출 랭킹',
    period: PERIOD_PRESETS.today7_30.recent30Days,
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  MNU_03_01: {
    code: 'MNU_03_01',
    label: '오늘 시간대별 메뉴 주문건수',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  MNU_04_01: {
    code: 'MNU_04_01',
    label: '오늘 식재료 소진량',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  MNU_05_04: {
    code: 'MNU_05_04',
    label: '최근 인기 메뉴 조합',
    period: PERIOD_PRESETS.recent7_14.recent7Days,
    type: CHART_TYPE.NUMBER,
    sizeX: 1,
    sizeY: 1,
  },
  WTH_01_01: {
    code: 'WTH_01_01',
    label: '오늘 날씨 예보',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.WEATHER,
    sizeX: 1,
    sizeY: 1,
  },
  WTH_02_01: {
    code: 'WTH_02_01',
    label: '오늘 시간별 예보',
    period: PERIOD_PRESETS.dayWeekMonth.today,
    type: CHART_TYPE.WEATHER,
    sizeX: 2,
    sizeY: 1,
  },
  WTH_03_04: {
    code: 'WTH_03_04',
    label: '주간 날씨 예보',
    period: PERIOD_PRESETS.recent7_14.recent7Days,
    type: CHART_TYPE.WEATHER,
    sizeX: 3,
    sizeY: 1,
  },
  WTH_04_07: {
    code: 'WTH_04_07',
    label: '강수 인사이트',
    period: PERIOD_PRESETS.recentMonths6_12.recent12Months,
    type: CHART_TYPE.RAIN,
    sizeX: 1,
    sizeY: 1,
  },
  WTH_05_07: {
    code: 'WTH_05_07',
    label: '강수 유무 판매채널별 주문건수 비율',
    period: PERIOD_PRESETS.recentMonths6_12.recent12Months,
    type: CHART_TYPE.RAIN,
    sizeX: 1,
    sizeY: 1,
  },
  WTH_06_07: {
    code: 'WTH_06_07',
    label: '강수 주문수 및 매출 변화',
    period: PERIOD_PRESETS.recentMonths6_12.recent12Months,
    type: CHART_TYPE.RAIN,
    sizeX: 1,
    sizeY: 1,
  },
} as const satisfies Record<string, MetricCard>;

export type MetricCardCode = keyof typeof DASHBOARD_METRIC_CARDS;

export const isMetricCardCode = (code: string): code is MetricCardCode => {
  return code in DASHBOARD_METRIC_CARDS;
};
